#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

KEY=/home/karl/ci.key
DIRECTORY=/home/karl/ci/build
REPOSITORY=https://github.com/karlspalding/ci.git

COMMIT=${1}

mkdir -p ${DIRECTORY}
git clone ${REPOSITORY} ${DIRECTORY}/${COMMIT}
cd ${DIRECTORY}/${COMMIT}
git crypt unlock ${KEY}
git reset --hard ${COMMIT}
yarn
yarn lint --format html --output-file www/eslint.html
yarn test
yarn build
rm -rf node_modules
yarn install --production
tar czf www/ci-${COMMIT}.tgz -C ${DIRECTORY} ${COMMIT}/dist ${COMMIT}/node_modules ${COMMIT}/README.md ${COMMIT}/package.json ${COMMIT}/yarn.lock ${COMMIT}/ecosystem.config.js
